export const skills = {
  software: [
    "Figma",
    "Sketch",
    "Framer",
    "Abstract",
    "Zeplin",
    "Photoshop",
    "Illustrator",
    "InDesign",
    "After Effects",
    "Adobe XD",
  ],
  process: [
    "Concept Design",
    "Wireframing",
    "User Research",
    "User Testing",
    "Research & Development",
    "Design Sprints",
    "Agile",
  ],
  development: [
    "HTML5",
    "CSS3",
    "Storybook",
    "Sass",
    "Javascript",
    "ES6",
    "Node",
    "Coffeescript",
    "React",
    "Git",
  ]
}