export const skills = {
  software: [
    "Figma",
    "Sketch",
    "Notion",
    "Framer",
    "Abstract",
    "Zeplin",
    "Photoshop",
    "Illustrator",
    "InDesign",
    "After Effects",
    "Adobe XD",
    "Powerpoint",
    "Keynote",
    "Excel",
  ],
  leadership: [
    "Management",
    "Coaching",
    "Strategy",
    "Vision",
    "Presentation",
    "OKR setting",
    "Prioritisation",
    "Cross-functional collaboration",
    "Analysis",
  ],
  process: [
    "Concept Design",
    "Wireframing",
    "User Research",
    "User Testing",
    "Research & Development",
    "Design Sprints",
    "Agile",
  ],
  development: [
    "HTML5",
    "CSS3",
    "Storybook",
    "Sass",
    "Javascript",
    "ES6",
    "Node",
    "Coffeescript",
    "React",
    "Git",
  ]
}